version: '3.8'

services:
  dashboard:
    build: .
    container_name: buan-dashboard
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./data/models:/app/data/models:delegated
      - ./data/raw:/app/data/raw
      - ./data/processed:/app/data/processed
      - ./data/logs:/app/data/logs
    env_file:
      - .env
    environment:
      - TRANSFORMERS_OFFLINE=1
      - HF_HUB_OFFLINE=1
      - HF_DATASETS_OFFLINE=1
      - TOKENIZERS_PARALLELISM=false
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - buan-network

networks:
  buan-network:
    driver: bridge 